### ISSUE TITLE
Please publish at Flathub

### ISSUE THREAD

**Issue by fastrizwaan** [mignaway/EpubReader#16]
Hi,

EpubReader is just a good looking software, it should be available to all Linux users, .deb only works with debian based distros. Please publish it at https://flathub.org/ 

https://flathub.org/setup

Here's a sample flatpak manifest, which does not work. I don't know how to package electron apps. but this may help you.

```
# io.github.mignaway.EpubReader
app-id: io.github.mignaway.EpubReader
base: org.electronjs.Electron2.BaseApp
base-version: '23.08'
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.node18
command: run.sh
separate-locales: false
finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=pulseaudio
  - --share=network
build-options:
  append-path: /usr/lib/sdk/node18/bin
  env:
    NPM_CONFIG_LOGLEVEL: info
modules:
  - name: electron-sample-app
    buildsystem: simple
    build-options:
      env:
        XDG_CACHE_HOME: /run/build/electron-sample-app/flatpak-node/cache
        npm_config_cache: /run/build/electron-sample-app/flatpak-node/npm-cache
        npm_config_offline: 'true'
    build-commands:
      # Install npm dependencies
      - npm install --offline
      # Build the app; in this example the `dist` script
      # in package.json runs electron-builder
      - |
        . ../flatpak-node/electron-builder-arch-args.sh
        npm run dist -- $ELECTRON_BUILDER_ARCH_ARGS  --linux --dir
      # Bundle app and dependencies
      - cp -a dist/linux*unpacked /app/main
      # Install app wrapper
      - install -Dm755 -t /app/bin/ ../run.sh
    subdir: main
    sources:
      - type: archive
        url: https://github.com/mignaway/EpubReader/archive/refs/tags/v1.0.5.tar.gz
        sha256: db951ca3860576e8810343b145009ccd3b5719185517b227950bb3caa27bbc9c
#      - type: dir
#        path: ..
#        dest: main
#      - generated-sources.json
#      # Wrapper to launch the app
      - type: script
        dest-filename: run.sh
        commands:
          - zypak-wrapper.sh /app/main/electron-sample-app "$@"
```

thank you.
